tasks/urls.py
from django.urls import path

from tasks.views import (
    TaskListView,
    TaskCreateView,
    TaskUpdateView,
    TaskDeleteView,
    TagListView,
    TagCreateView,
    TagUpdateView,
    TagDeleteView,
    change_completed_status
)

urlpatterns = [
    path("", TaskListView.as_view(), name="task-list"),
    path("task/create/", TaskCreateView.as_view(), name="task-create"),
    path("task/<int:pk>/update/", TaskUpdateView.as_view(), name="task-update"),
    path("task/<int:pk>/delete/", TaskDeleteView.as_view(), name="task-delete"),
    path("task/<int:pk>/complete/", change_completed_status, name="task-complete"),
    path("tags/", TagListView.as_view(), name="tag-list"),
    path("tags/create/", TagCreateView.as_view(), name="tag-create"),
    path("tags/<int:pk>/update/", TagUpdateView.as_view(), name="tag-update"),
    path("tags/<int:pk>/delete/", TagDeleteView.as_view(), name="tag-delete")
]

app_name = "tasks"

todo_list/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('tasks.urls', namespace='tasks'))
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

tasks/models.py
from django.db import models


class Task(models.Model):
    content = models.CharField(max_length=255)
    created_at = models.DateTimeField(auto_now_add=True)
    deadline_at = models.DateTimeField(blank=True, null=True)
    completed = models.BooleanField()
    tags = models.ManyToManyField("Tag", related_name="tags")

    class Meta:
        ordering = ["completed", "-created_at"]


class Tag(models.Model):
    name = models.CharField(max_length=65, unique=True)

    class Meta:
        ordering = ["name"]

    def __str__(self):
        return f"{self.name}"

tasks/forms.py
from django import forms

from tasks.models import Task, Tag


class TaskForm(forms.ModelForm):
    tags = forms.ModelMultipleChoiceField(
        queryset=Tag.objects.all(),
        widget=forms.CheckboxSelectMultiple,
        required=False
    )

    class Meta:
        model = Task
        fields = "__all__"

tasks/views.py
from django.urls import reverse_lazy
from django.views import generic
from django.shortcuts import redirect

from tasks.models import Task, Tag
from tasks.forms import TaskForm


class TaskListView(generic.ListView):
    model = Task
    paginate_by = 5


class TaskCreateView(generic.CreateView):
    model = Task
    form_class = TaskForm
    success_url = reverse_lazy("tasks:task-list")
    template_name = "tasks/task_form.html"


class TaskUpdateView(generic.UpdateView):
    model = Task
    form_class = TaskForm
    success_url = reverse_lazy("tasks:task-list")
    template_name = "tasks/task_form.html"


class TaskDeleteView(generic.DeleteView):
    model = Task
    success_url = reverse_lazy("tasks:task-list")
    template_name = "tasks/task_confirm_delete.html"


class TagListView(generic.ListView):
    model = Tag
    paginate_by = 5


class TagCreateView(generic.CreateView):
    model = Tag
    fields = "__all__"
    success_url = reverse_lazy("tasks:tag-list")
    template_name = "tasks/tag_form.html"


class TagUpdateView(generic.UpdateView):
    model = Tag
    fields = "__all__"
    success_url = reverse_lazy("tasks:tag-list")
    template_name = "tasks/tag_form.html"


class TagDeleteView(generic.DeleteView):
    model = Tag
    success_url = reverse_lazy("tasks:tag-list")
    template_name = "tasks/tag_confirm_delete.html"


def change_completed_status(request, pk):
    task = Task.objects.get(id=pk)
    task.completed = not task.completed
    task.save()
    return redirect("tasks:task-list")

templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    {% block title %}<title>Todo List</title>{% endblock %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet"
          href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css"
          integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2"
          crossorigin="anonymous">
    <!-- Add additional CSS in static file -->
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    <link rel="icon" type="image/png" href="{% static "images/favicon.png" %}">
</head>

<body>
<div class="container-fluid">
    <div class="row">
        <div class="col-sm-2">

            {% block sidebar %}
                {% include "includes/sidebar.html" %}
            {% endblock %}

        </div>
        <div class="col-sm-10 ">

            {% block content %}{% endblock %}
                <br>
            {% block pagination %}
                {% include "includes/pagination.html" %}
            {% endblock %}

        </div>
    </div>
</div>
</body>

</html>

templates/includes/pagination.html
{% if is_paginated %}

  <ul class="pagination">
    {% if page_obj.has_previous %}
      <li class="page-item">
        <a href="?page= {{ page_obj.previous_page_number }}" class="page-link">prev</a>
      </li>
    {% endif %}
    <li class="page-item active">
      <span class="page-link">{{ page_obj.number }} of {{ paginator.num_pages }}</span>
    </li>
    {% if page_obj.has_next %}
      <li class="page-item">
        <a href="?page= {{ page_obj.next_page_number }}" class="page-link">next</a>
      </li>
    {% endif %}
  </ul>

{% endif %}

templates/includes/sidebar.html
<ul class="sidebar-nav list-group">
  <li class="list-group-item"><a href="{% url "tasks:task-list" %}">Home</a></li>
  <li class="list-group-item"><a href="{% url "tasks:tag-list" %}">Tags</a></li>
</ul>

templates/tasks/tag_confirm_delete.html
{% extends "base.html" %}

{% block content %}

  <h1>Delete Tag</h1>

  <p>Are you sure that you want to delete this tag: <strong>{{ tag.name }}?</strong></p>

  <form action="" method="POST">
    {% csrf_token %}
    <input type="submit" value="Yes, delete" class="btn btn-danger"/>
  </form>

{% endblock %}

templates/tasks/tag_form.html
{% extends "base.html" %}

{% block content %}

  <h1>{{ object|yesno:"Update,Add" }} Tag</h1>

  <form action="" method="post" novalidate>
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Submit" class="btn btn-primary"/>
  </form>

{% endblock %}

templates/tasks/tag_list.html
{% extends "base.html" %}

{% block content %}

  <h1>
    Tags
    <form action="{% url "tasks:tag-create" %}" style="float: right">
      {% csrf_token %}
      <input type="submit" value="Add" class="btn btn-success"/>
    </form>
  </h1>
  <br>
  {% if tag_list %}
  <table class="table">
    <tr>
      <th>Username</th>
      <th>Update</th>
      <th>Delete</th>
    </tr>
  {% for tag in tag_list %}
    <tr>
      <td>{{ tag.name }}</td>
      <td>
        <form action="{% url "tasks:tag-update" pk=tag.id %}">
          {% csrf_token %}
          <input type="submit" value="Update" class="btn btn-warning"/>
        </form>
      </td>
      <td>
        <form action="{% url "tasks:tag-delete" pk=tag.id %}">
          {% csrf_token %}
          <input type="submit" value="Delete" class="btn btn-danger"/>
        </form>
      </td>
    </tr>
  {% endfor %}

  </table>
  {% else %}
    <p>There are no tags in your TODO list.</p>
  {% endif %}

{% endblock %}

templates/tasks/task_confirm_delete.html
{% extends "base.html" %}

{% block content %}

  <h1>Delete Task</h1>

  <p>Are you sure that you want to delete this task: <strong>{{ task.content }}?</strong></p>

  <form action="" method="POST">
    {% csrf_token %}
    <input type="submit" value="Yes, delete" class="btn btn-danger"/>
  </form>

{% endblock %}

templates/tasks/task_form.html
{% extends "base.html" %}

{% block content %}

  <h1>{{ object|yesno:"Update,Create" }} Task</h1>
  <form action="" method="post" novalidate>
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Submit" class="btn btn-primary"/>
  </form>

{% endblock %}

templates/tasks/task_list.html
{% extends "base.html" %}

{% block content %}

  <h1>
    TODO list
    <form action="{% url "tasks:task-create" %}" style="float: right">
      {% csrf_token %}
      <input type="submit" value="Create Task" class="btn btn-primary"/>
    </form>
  </h1>
    <div class="line"></div>
    <br>
    <br>

  {% if task_list %}
    {% for task in task_list %}
      <h4>
        <strong>{{ task.content }}</strong>
        {% if task.completed %}
          <strong style="color: green">Done</strong>
        {% else %}
          <strong style="color: red">Not done</strong>
        {% endif %}
        {% if task.completed %}
          <form action="{% url "tasks:task-complete" pk=task.id %}" style="float: right">
            {% csrf_token %}
            <input type="submit" value="Undo" class="btn btn-secondary"/>
          </form>
        {% else %}
          <form action="{% url "tasks:task-complete" pk=task.id %}" style="float: right">
            {% csrf_token %}
            <input type="submit" value="Complete" class="btn btn-success"/>
          </form>
        {% endif %}
      </h4>
      <p>
        Created: {{ task.created_at }}
        <span style="color: brown">
          {% if task.deadline_at %}Deadline: {{ task.deadline_at }}{% endif %}
        </span>
      </p>
      <h5>
        Tags: {% for tag in task.tags.all %}{{ tag.name }} {% endfor %}
        <a href="{% url "tasks:task-update" pk=task.id %}">Update</a>
        <a href="{% url "tasks:task-delete" pk=task.id %}">Delete</a>
      </h5>
      <hr>
    {% endfor %}
  {% else %}
    <p>There are no tasks in your TODO list</p>
  {% endif %}

{% endblock %}